web:
    build: phpimg
    ports:
        - "80:80"
    volumes:
        - /var/www:/var/www/html
        - /var/www/docker/php.ini:/usr/local/etc/php/conf.d/30-custom.ini
        - /var/www/docker/sites:/etc/apache2/sites-enabled
    environment:
        - ALLOW_OVERRIDE=true
    links:
        - db:db
        - elasticsearch:elasticsearch
        - memcached:memcached

db:
    image: mysql
    volumes:
        - /var/lib/boot2docker/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root

elasticsearch:
    image: elasticsearch:1.7
    ports:
        - "9200:9200"
        - "9300:9300"
memcached:
    image: memcached:1.4
